[package]
name = "kinopio"
version = "0.1.0"
description = "Kinopio desktop app"
authors = ["pirijan"]
license = ""
repository = ""
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# capitalized so that the dock shows "Kinopio" when running in development
[[bin]]
name = "Kinopio"
path = "src/main.rs"

[lib]
name = "kinopio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1", features = ["devtools"] }
tauri-plugin-log = "2"
tauri-plugin-opener = "2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3", default-features = false, features = ["NSWindow", "NSGraphics", "NSResponder"] }
